### ISSUE TITLE
handle 404 responses from pulse more gracefully

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/-nanobox-io-nanobox-dash-ui-valkrie#1]
When an app is first launched pulse won't have stats for it yet. Currently this results in 404 errors in the js console.

![image](https://cloud.githubusercontent.com/assets/313947/19984010/fa0e59f6-a1d1-11e6-8ff5-d7d053f0699e.png)

**Comment by Tolmark12** [comment]
I've been looking around and I'm not seeing any way to catch those errors. We already have a handler that is notified when the request fails, but there isn't really the equivalent of an ajax try / catch to prevent them from being printed to the console.

**Comment by Tolmark12** [comment]
We could try to determine if pulse and the component are alive and available and not make the request if it's they aren't available if we wanted to, but I don't think it's currently hurting to have those requests fail.

**Comment by jedgalbraith** [comment]
Whatever you think. We just had a user point it out and thought it was an oversight.

**Comment by Tolmark12** [comment]
I'd close for now unless we can find someway of not printing `502` errors to the console.

**Comment by Tolmark12** [comment]
If we wanted to handle this server-side that's an option:
http://stackoverflow.com/questions/11949095/how-can-i-stop-jquery-ajax-from-logging-failures-to-the-console

**Comment by jedgalbraith** [comment]
We could use the `isPlatformReady` attribute and not make requests until then.

**Comment by Tolmark12** [comment]
I think it would still fail even if the platform is ready but the component isn't online yet, no?

**Comment by jedgalbraith** [comment]
oh, yeah. That's true. I was thinking this was limited to the platform services not being ready, but it could happen with any new component. yeah, let's close it.

**Comment by Tolmark12** [comment]
cool, I agree since it's just something that shows up in the browser console but doesn't affect the user.
