### ISSUE TITLE
exclude non-active hosts from move options

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/-nanobox-io-nanobox-dash-ui-valkrie#4]
We need to exclude non-active hosts from the component move options.

Sample valkrie data with a provisioning host: https://gist.github.com/jedgalbraith/05505030ade6b4852a7366673d229664

![screen shot 2017-01-25 at 11 45 34 am](https://cloud.githubusercontent.com/assets/313947/22304298/101ec4ac-e2f4-11e6-9f1f-476001b33d6d.png)

**Comment by Tolmark12** [comment]
Fixed, waiting to build / deploy
