### ISSUE TITLE
host and component admin actions need to handle 401 unauthorized responses

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/-nanobox-io-nanobox-dash-ui-valkrie#9]
It looks like the paths for host and component actions like reboot, refresh, rebuild are hard coded into valkrie. Is that right? I don't see anything in the implementation of the component where we pass those paths in.

If that the case, I'm wondering if the best way to go about this would be to expose all actions via the component config so Odin can handle unauthorized responses like it does for other component actions. Otherwise valkrie will need to handle 401 responses directly.

**Comment by Tolmark12** [comment]
currently, we know what url to call based on the `actionUrl`.

We then build the desired url and send a `PATCH` ajax request like so 

URL :
```coffeescript
"#{actionUrl}/#{action}"
# "/some/action/path/reboot"
```

Possible actions:
```
refresh
reboot
rebuild
update_service
manage
delete       # When deleting, we send a `DELETE` instead of `PATCH`
```

**Comment by jedgalbraith** [comment]
Ok. So how do you think we should handle 401/unauthorized responses?

**Comment by Tolmark12** [comment]
What do we need to do on a 401?

**Comment by jedgalbraith** [comment]
Notify the user that they're unauthorized to perform the action. For responses that Odin is in control of, we pop up a modal.

![screen shot 2017-06-06 at 3 12 31 pm](https://user-images.githubusercontent.com/313947/26852166-9cbddbf8-4aca-11e7-8663-4145255dc07e.png)

**Comment by jedgalbraith** [comment]
Or we need to hide the action so the user doesn't attempt it in the first place.

**Comment by Tolmark12** [comment]
gotcha that makes sense. Here's a few options:

1. Use callbacks so that odin handles the 401 w/ a popup (pattern followed in other components)
2. Provide a `showUnauthorized` callback that shows that popup and have valkrie call that if it gets a 401
3. Pass in a list of allowed actions so valkrie can grey out or hide unavailable actions, preventing unauthorized calls

**Comment by Tolmark12** [comment]
The following will be added to the valkrie config :
( 

```
hostActions: [
  {action:'refresh', permission:true}
  {action:'reboot',  permission:false} # permission `false` if user not allowed to do this action
  {action:'rebuild', permission:true}
  {action:'update',  permission:true}
  {action:'manage',  permission:true}
  {action:'delete',  permission:true}
]

componentActions : [
  # same pattern as above
]

callbacks :
  # other callbacks..
  onHostAction      : (hostId, action, cb)->
  onComponentAction : (componentId, action, cb)->
```

(Based on offline conversation)

**Comment by Tolmark12** [comment]
JS components Deployed; bower update `clobberbox` and `valkrie`
